# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: HospitalAppointment.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'HospitalAppointment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19HospitalAppointment.proto\"\x81\x01\n\x0b\x41ppointment\x12\x15\n\rappointmentId\x18\x01 \x01(\x05\x12\x13\n\x0bpatientName\x18\x02 \x01(\t\x12\x12\n\ndoctorName\x18\x03 \x01(\t\x12\x12\n\ndepartment\x18\x04 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x05 \x01(\t\x12\x10\n\x08timeSlot\x18\x06 \x01(\t\"\x19\n\nBoolResult\x12\x0b\n\x03res\x18\x01 \x01(\x08\"&\n\rAppointmentId\x12\x15\n\rappointmentId\x18\x01 \x01(\x05\"\"\n\x0bPatientName\x12\x13\n\x0bpatientName\x18\x01 \x01(\t\"5\n\x0f\x41ppointmentList\x12\"\n\x0c\x61ppointments\x18\x01 \x03(\x0b\x32\x0c.Appointment\"\x07\n\x05\x45mpty\"\x1b\n\x0bStorageSize\x12\x0c\n\x04size\x18\x01 \x01(\x05\x32\xf9\x01\n\x12\x41ppointmentService\x12,\n\x0f\x62ookAppointment\x12\x0c.Appointment\x1a\x0b.BoolResult\x12)\n\tqueryById\x12\x0e.AppointmentId\x1a\x0c.Appointment\x12\x30\n\x0equeryByPatient\x12\x0c.PatientName\x1a\x10.AppointmentList\x12\x30\n\x11\x63\x61ncelAppointment\x12\x0e.AppointmentId\x1a\x0b.BoolResult\x12&\n\x0egetStorageSize\x12\x06.Empty\x1a\x0c.StorageSizeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HospitalAppointment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APPOINTMENT']._serialized_start=30
  _globals['_APPOINTMENT']._serialized_end=159
  _globals['_BOOLRESULT']._serialized_start=161
  _globals['_BOOLRESULT']._serialized_end=186
  _globals['_APPOINTMENTID']._serialized_start=188
  _globals['_APPOINTMENTID']._serialized_end=226
  _globals['_PATIENTNAME']._serialized_start=228
  _globals['_PATIENTNAME']._serialized_end=262
  _globals['_APPOINTMENTLIST']._serialized_start=264
  _globals['_APPOINTMENTLIST']._serialized_end=317
  _globals['_EMPTY']._serialized_start=319
  _globals['_EMPTY']._serialized_end=326
  _globals['_STORAGESIZE']._serialized_start=328
  _globals['_STORAGESIZE']._serialized_end=355
  _globals['_APPOINTMENTSERVICE']._serialized_start=358
  _globals['_APPOINTMENTSERVICE']._serialized_end=607
# @@protoc_insertion_point(module_scope)
